# Generated by Django 4.2.5 on 2023-09-17 23:31

from django.db import migrations, models
import django.db.models.deletion
import firmware_manager.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Directory",
            fields=[
                ("owner", models.IntegerField()),
                ("group", models.IntegerField()),
                ("setuid", models.BooleanField()),
                ("sticky", models.BooleanField()),
                ("perms", models.IntegerField()),
                ("created", models.BigIntegerField()),
                ("modified", models.BigIntegerField()),
                ("islink", models.BooleanField()),
                ("size", models.IntegerField()),
                ("mime", models.CharField(max_length=255)),
                ("magic", models.CharField(max_length=255)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("isroot", models.BooleanField(default=False)),
                ("rname", models.CharField(blank=True, default="", max_length=255)),
                ("rparent", models.CharField(blank=True, default="", max_length=255)),
                (
                    "directories",
                    models.ManyToManyField(
                        related_name="subdirectories", to="firmware_manager.directory"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Firmware",
            fields=[
                ("name", models.CharField(max_length=255)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("hash", models.CharField(max_length=64)),
                ("size", models.PositiveIntegerField()),
                (
                    "location",
                    models.FileField(
                        upload_to=firmware_manager.models.firmware_upload_location
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RawFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner", models.IntegerField()),
                ("group", models.IntegerField()),
                ("setuid", models.BooleanField()),
                ("sticky", models.BooleanField()),
                ("perms", models.IntegerField()),
                ("created", models.BigIntegerField()),
                ("modified", models.BigIntegerField()),
                ("islink", models.BooleanField()),
                ("size", models.IntegerField()),
                ("mime", models.CharField(max_length=255)),
                ("magic", models.CharField(max_length=255)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                ("owner", models.IntegerField()),
                ("group", models.IntegerField()),
                ("setuid", models.BooleanField()),
                ("sticky", models.BooleanField()),
                ("perms", models.IntegerField()),
                ("created", models.BigIntegerField()),
                ("modified", models.BigIntegerField()),
                ("islink", models.BooleanField()),
                ("size", models.IntegerField()),
                ("mime", models.CharField(max_length=255)),
                ("magic", models.CharField(max_length=255)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="firmware_manager.directory",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="directory",
            name="files",
            field=models.ManyToManyField(
                related_name="subfiles", to="firmware_manager.file"
            ),
        ),
        migrations.AddField(
            model_name="directory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="firmware_manager.directory",
            ),
        ),
    ]
