# Generated by Django 4.2.5 on 2023-09-18 00:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("firmware_manager", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="directory",
            name="directories",
        ),
        migrations.RemoveField(
            model_name="directory",
            name="files",
        ),
        migrations.RemoveField(
            model_name="directory",
            name="isroot",
        ),
        migrations.AlterField(
            model_name="directory",
            name="created",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="directory",
            name="modified",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="rawfile",
            name="created",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="rawfile",
            name="modified",
            field=models.TimeField(),
        ),
    ]
