# Generated by Django 4.2.5 on 2023-09-18 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "firmware_manager",
            "0002_remove_directory_directories_remove_directory_files_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="directory",
            name="created",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="directory",
            name="modified",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="rawfile",
            name="created",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="rawfile",
            name="modified",
            field=models.BigIntegerField(),
        ),
    ]
