# Generated by Django 4.2.4 on 2023-09-21 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
        ('firmware_manager', '0003_alter_directory_created_alter_directory_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmware',
            name='admin_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firmwares', to='user_auth.organisationmodel'),
        ),
        migrations.AddField(
            model_name='firmware',
            name='shared_orgs',
            field=models.ManyToManyField(blank=True, null=True, related_name='shared_firmwares', to='user_auth.organisationmodel'),
        ),
    ]
