# Generated by Django 4.2.4 on 2023-09-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
        ('firmware_manager', '0004_firmware_admin_org_firmware_shared_orgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmware',
            name='shared_orgs',
            field=models.ManyToManyField(blank=True, related_name='shared_firmwares', to='user_auth.organisationmodel'),
        ),
    ]
