# Generated by Django 4.2.4 on 2023-10-02 20:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('firmware_manager', '0007_alter_directory_created_alter_directory_modified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firmware',
            old_name='size',
            new_name='file_size',
        ),
        migrations.AddField(
            model_name='firmware',
            name='failure_reason',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='firmware',
            name='file_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firmware',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='firmware',
            name='md5',
            field=models.CharField(default=django.utils.timezone.now, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firmware',
            name='sha1',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firmware',
            name='sha256',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firmware',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('failed', 'Failed'), ('running', 'Running'), ('done', 'Done')], default='submitted', max_length=255),
        ),
    ]
