# Generated by Django 4.2.4 on 2023-10-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firmware_manager', '0010_alter_file_modified_alter_firmware_failure_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmware',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='firmware',
            name='file_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='firmware',
            name='hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
